language: python
python:
  - "3.7"
os: linux
dist: xenial
cache:
  pip: true
  yarn: true
  directories:
    - $HOME/buildout-cache
    - ~/.cache
addons:
  apt:
    packages:
      - xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
before_install:
  - nvm install 12;
install:
  - yarn install --frozen-lockfile
  - yarn cy:install
script:
  - echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc;
  - yarn ci:cypress:run:guillotina;
