language: python
dist: xenial
matrix:
  include:
    - name: 'Plone'
      python: 3.7
      env: TEST_SUITE=plone ZSERVER_PORT=55001
    - name: 'Guillotina Tests'
      python: 3.7
      env: TEST_SUITE=guillotina
    - name: 'Unit Tests'
      env: TEST_SUITE=unit
cache:
  pip: true
  yarn: true
  directories:
    - $HOME/buildout-cache
    - ~/.cache
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
before_install:
  - nvm install 10.14.2;
  - if [ "$TEST_SUITE" != "plone" ]; then
    docker build -t plone/volto:testing .;
    fi
  - if [ "$TEST_SUITE" == "plone" ]; then
    mkdir -p $HOME/buildout-cache/{eggs,downloads};
    mkdir $HOME/.buildout;
    echo "[buildout]" > $HOME/.buildout/default.cfg;
    echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg;
    echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg;
    fi

install:
  - if [ "$TEST_SUITE" == "plone" ]; then
    make build-backend;
    fi
  - yarn install --frozen-lockfile
  - yarn cy:install
script:
  - yarn run prettier
  - yarn run lint
  - if [ "$TEST_SUITE" == "unit" ]; then
    docker run --name coverage_front -it --rm -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" plone/volto:testing -- yarn test:ci;
    fi
  - if [ "$TEST_SUITE" == "guillotina" ]; then
    yarn ci:cypress:run:guillotina;
    fi
  - if [ "$TEST_SUITE" == "plone" ]; then
    yarn ci:cypress:run;
    fi
after_success:
  - if [ "$TEST_SUITE" == "plone" ]; then
    yarn run bundlewatch;
    yarn run bundlesize;
    fi
  - if [ "$TEST_SUITE" == "guillotina" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker tag plone/volto:testing plone/volto:$TRAVIS_BRANCH.$TRAVIS_COMMIT;
    docker push plone/volto:$TRAVIS_BRANCH.$TRAVIS_COMMIT;
    docker tag plone/volto:testing plone/volto:$TRAVIS_BRANCH.green;
    docker push plone/volto:$TRAVIS_BRANCH.green;
    fi

# safelist
branches:
  only:
    - master
