sudo: false
language: python
python:
- 2.7.14
cache:
  pip: true
  directories:
   - node_modules
before_install:
- nvm install 8.11.2
- mkdir webdriver
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
- tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C webdriver
- export PATH=$PATH:$(pwd)/webdriver
install:
- virtualenv env --python=$(which python) --no-site-packages
- env/bin/pip install zc.recipe.egg==2.0.4 --no-cache-dir
- env/bin/pip install -r api/docker/requirements.txt
- env/bin/pip install -U https://github.com/zopefoundation/z3c.autoinclude/archive/pip.tar.gz#egg=z3c.autoinclude
- yarn
- yarn build
script:
- yarn coverage
- PYTHONPATH=$(pwd)/tests env/bin/pybot -v BROWSER:headlessfirefox tests
