language: python
os: linux
dist: xenial
jobs:
  include:
    - name: 'Plone'
      python: 3.7
      env: TEST_SUITE=plone ZSERVER_PORT=55001
    - name: 'Guillotina Tests'
      python: 3.7
      env: TEST_SUITE=guillotina
    - name: 'Unit Tests'
      env: TEST_SUITE=unit
cache:
  pip: true
  yarn: true
  directories:
    - $HOME/buildout-cache
    - ~/.cache
addons:
  apt:
    packages:
      - xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
before_install:
  - nvm install 12;
  - if [ "$TEST_SUITE" == "plone" ]; then
    mkdir -p $HOME/buildout-cache/{eggs,downloads};
    mkdir $HOME/.buildout;
    echo "[buildout]" > $HOME/.buildout/default.cfg;
    echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg;
    echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg;
    fi
  - npm install -g surge
install:
  - if [ "$TEST_SUITE" == "plone" ]; then
    (cd api && pip install -r requirements.txt) &&
    (cd api && buildout)
    fi
  - yarn install --frozen-lockfile
  - yarn cy:install
script:
  - if [ "$TEST_SUITE" == "unit" ]; then
    yarn run prettier &&
    yarn run lint &&
    yarn run code-analysis:i18n &&
    yarn test:ci;
    fi
  - if [ "$TEST_SUITE" == "guillotina" ]; then
    echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc;
    yarn ci:cypress:run:guillotina;
    fi
  - if [ "$TEST_SUITE" == "plone" ]; then
    echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc;
    yarn ci:cypress:run;
    fi
after_script:
  - mkdir cypress-results
  - mv cypress/videos cypress-results
  - ls -al cypress-results
  - surge cypress-results volto.surge.sh
  - echo "Cypress Videos uploaded to http://volto.surge.sh/videos/blocks.js.mp4"
after_success:
  - if [ "$TEST_SUITE" == "plone" ]; then
    yarn run bundlewatch;
    yarn run bundlesize;
    fi
