version: '3.3'
services:
    plone:
        container_name: plone
        ports:
            - '8080:8080'
        environment:
            - SITE=Plone
            - ADDONS=kitconcept.volto
            - ZCML=kitconcept.volto.cors
            - 'PROFILES=kitconcept.volto:default-homepage'
        image: plone
    frontend:
        ports:
            - '3000:3000'
        image: 'plone/volto:slim'
        # Use just 'plone/volto' image and set the env var in case you want to
        # use any released Volto addons
        # image: 'plone/volto'
        # environment:
        #     - ADDONS="volto-slate:asDefault"
